version: "3.9"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "sbis"
      POSTGRES_USER: "sbis"
      POSTGRES_PASSWORD: "sbis"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ./tmp:/var/lib/postgresql/data
    ports:
      - "5433:5432"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G